# Generated by Django 5.1.3 on 2024-12-03 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'permissions': [('custom_view_location', 'Can view location'), ('custom_change_location', 'Can change location')]},
        ),
    ]
