# Generated by Django 5.1.3 on 2024-12-03 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_alter_location_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={},
        ),
    ]
